buckets:
  art-public:
    description: contains low‑res thumbnails, css, site assets
    policy: public-read
    endpoints:
      subdomain: https://cdn.artalytics.art
      origin: https://art-public.sfo3.digitaloceanspaces.com
      cdn: https://art-public.sfo3.cdn.digitaloceanspaces.com
    access:
      - scope: write
        key_id: DO00KPUXQBXYKTULMGN7
        key: !expr Sys.getenv("ART_BUCKETS_WRITE_KEY")

  art-coa:
    description: contains certificate files (PDFs/JPEGs)
    policy: public-read
    endpoints:
      subdomain: https://cdn.certificates.art
      origin: https://art-coa.sfo3.digitaloceanspaces.com
      cdn: https://art-coa.sfo3.cdn.digitaloceanspaces.com
    access:
      - scope: write
        key_id: DO00KPUXQBXYKTULMGN7
        key: !expr Sys.getenv("ART_BUCKETS_WRITE_KEY")

  art-data:
    description: contains files, images, and other assets used by platform
    policy: private
    endpoints:
      origin: https://art-data.sfo3.digitaloceanspaces.com
      cdn: https://art-data.sfo3.cdn.digitaloceanspaces.com
    access:
      - scope: read
        key_id:  DO801KZVR3X3UWDE6GGN
        key: !expr Sys.getenv("ART_BUCKETS_READ_KEY")
      - scope: write
        key_id: DO00KPUXQBXYKTULMGN7
        key: !expr Sys.getenv("ART_BUCKETS_WRITE_KEY")

  art-vault:
    description: contains the file bundles uploaded by artists
    policy: private
    endpoints:
      origin: https://art-vault.sfo3.digitaloceanspaces.com
      cdn: https://art-vault.sfo3.cdn.digitaloceanspaces.com
    access:
      - scope: read
        key_id: DO801KZVR3X3UWDE6GGN
        key: !expr Sys.getenv("ART_BUCKETS_READ_KEY")
      - scope: write
        key_id: DO00KPUXQBXYKTULMGN7
        key: !expr Sys.getenv("ART_BUCKETS_WRITE_KEY")
